create flower, bouquets, shop classes
ValeriyaKot/trainee_tasks pull request #2
Opened 2021-02-15 14:35 UTC by ValeriyaKot

2021-02-15 16:53 UTC, m4qo5 requested changes

2021-02-15 16:53 UTC, m4qo5 commented on flower-shop/flower_shop.py
> +order_list = []
Please think about way of storing this data inside Shop class

2021-02-15 16:53 UTC, m4qo5 commented on flower-shop/flower_shop.py
> +        self.color = color
Use a enum sequence to store flower types rather than defining an attribute:
more about enums here: https://docs.python.org/3/library/enum.html

2021-02-15 16:53 UTC, m4qo5 commented on flower-shop/flower_shop.py
> +        self.color = color
Add an ability to compare Flower's (are they equal or not, hint: `__eq__`)

Could it be like this; if Flower's types are different then they're not equal. If two flowers have equal flower types then they're equal.

2021-02-15 16:53 UTC, m4qo5 commented on flower-shop/flower_shop.py
> +                continue
Create a separate function(s) that will check whether or not we can sell / order something and if we can't raise a `ValueError` or another suitable exception

2021-02-15 16:53 UTC, m4qo5 commented on flower-shop/flower_shop.py
> +        self.color = color
Add `__str__` methods to classes

2021-02-15 16:53 UTC, m4qo5 commented on flower-shop/flower_shop.py
> +flowers_list = []
Explain why you have decided to use list as a main flower data storage? 

Imagine the situation when we have bouquets with different flowers, and with different flowers quantity

Like this: Bouquet Alpha (Roses: 5, Lilys: 8, SomeFlower: 3)
And the same way Shop could have Bouquet Alpha : 5, Another Bouquet: 8

Wouldn't it be better to use dictionary in this situation?

2021-02-16 11:46 UTC, ValeriyaKot commented
I added magic methods. I did refactoring my code

2021-02-16 12:40 UTC, m4qo5 approved these changes

2021-02-16 13:23 UTC, merged